name: Best Buy CI/CD

on:
  push:
    branches:
      - main
      # min, hr,dd,mm,dow (0-7)

jobs:
  Build-and-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Tests with pytest
        if: github.ref == 'refs/heads/main'
        run: |
          pytest

      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: best-buy
          path: target/*.war

      - name: Notify if Build Fails
        if: failure()
        run: echo "Build job failed! Please check logs"